name: Publish Package
on:
  push:
    branches:
      - master
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
      - run: |
          echo "Setting up secrets."
          echo "Secrets loaded!"
          echo "$MAVEN_PASSWORD" | sha256sum
          cat ~/.m2/settings.xml
        shell: bash
        env:
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Check SNAPSHOT
        id: check_snapshot
        run: |
          if mvn help:evaluate -Dexpression=project.version -q -DforceStdout | grep -q SNAPSHOT; then
            echo "::set-output name=is_snapshot::true"
          else
            echo "::set-output name=is_snapshot::false"
          fi
      - name: Publish Nexus Package
        if: steps.check_snapshot.outputs.is_snapshot == 'true'
        run: mvn -P release -B clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}